# .github/workflows/pr-build.yml
name: Pull Request SideStore build
on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build-and-upload.yml
    with:
      app_name: AnisetteLister
      change_version: |
        sed -e "/MARKETING_VERSION = .*/s/\$/-pr.${{ github.event.pull_request.number }}+$(git rev-parse --short ${COMMIT:-HEAD})/" -i '' Config/Base.xcconfig
      version_suffix: "-pr.${{ github.event.pull_request.number }}+$(git rev-parse --short ${COMMIT:-HEAD})"

